services:
  - type: web
    name: sitewise-bot
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
